!Include ../defaults.in.yml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      labels:
        stack: tracontent
        component: setup
    spec:
      containers:
      - name: setup
        image: !Var tracontent_image
        args: ["python", "manage.py", "setup"]
        env: !Var environment
      restartPolicy: Never
  backoffLimit: 4
