version: '2.2'
services:
  web:
    build: .
    init: true
    command: scripts/wait-for-it.sh postgres:5432 -- python manage.py docker_start
    ports:
      - 8001:8001
    links:
      - postgres
    volumes:
      - tracontent-media:/usr/src/app/media
      - .:/usr/src/app
    environment:
      PYTHONUNBUFFERED: 1
      DEBUG: 1
      DATABASE_URL: psql://tracontent:secret@postgres/tracontent
      TRACONTENT_SITE: tracon2019
      TRACONTENT_HOSTNAME: localhost
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tracontent
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tracontent
volumes:
  postgres-data:
    driver: local
  tracontent-media:
    driver: local
