apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: edegal

build:
  local:
    useBuildkit: true
  artifacts:
    - image: tracontent
      context: .
    - image: tracontent-static
      context: .
      docker:
        dockerfile: Dockerfile.static
      requires:
        - image: tracontent
          alias: BACKEND_IMAGE

deploy:
  kubectl:
    manifests:
      - kubernetes/template.compiled.yaml
