apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      stack: tracontent
      component: nginx
  template:
    metadata:
      labels:
        stack: tracontent
        component: nginx
    spec:
      enableServiceLinks: false
      containers:
        - name: master
          image: !Var tracontent_static_image
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/media
              name: tracontent-media
      volumes: !Var tracontent_media_volumes_definition
