apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracontent
spec:
  selector:
    matchLabels:
      stack: tracontent
      component: tracontent
  template:
    metadata:
      labels:
        stack: tracontent
        component: tracontent
    spec:
      containers:
      - name: master
        image: !Var tracontent_image
        ports:
        - containerPort: 8000
        env: !Var environment
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 8000
            httpHeaders:
              - name: Host
                value: !Lookup ingress_public_hostnames[0]
          initialDelaySeconds: 15
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 8000
            httpHeaders:
              - name: Host
                value: !Lookup ingress_public_hostnames[0]
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
          - !If
              test: !Var tracontent_enable_volumes
              then:
                mountPath: /usr/src/app/media
                name: tracontent-media
      volumes:
        - !If
            test: !Var tracontent_enable_volumes
            then:
              name: tracontent-media
              persistentVolumeClaim:
                claimName: tracontent-media
