apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    stack: tracontent
    component: tracontent
  name: tracontent-media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
