apiVersion: v1
kind: Secret
metadata:
  name: tracontent
  labels:
    stack: tracontent
  annotations: !If
    test: !Var tracontent_secret_key
    then: !Void
    else:
      secret-generator.v1.mittwald.de/autogenerate: secretKey
type: Opaque
data:
  kompassiClientId: !Base64 ""
  kompassiClientSecret: !Base64 ""
  secretKey: !If
    test: !Var tracontent_secret_key
    then: !Base64,Var tracontent_secret_key