apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    stack: tracontent
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    stack: tracontent
    component: redis
