ingress_public_hostnames:
  - con2.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: con2
postgres_username: con2
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_cache_database: 2

tracontent_secret_managed: false
tracontent_storage_pvc: true
tracontent_storage_pvc_storageclass: longhorn-nfs

tracontent_editor_groups:
  - con2-staff

tracontent_admins:
  - Santtu Pajukanta <santtu@pajukanta.fi>

smtp_server: sr1.pahaip.fi
smtp_default_from_email: root@tracon.fi

setup_should_run: true

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
