!Defaults

tracontent_tag: staging
tracontent_image: !Format tracon/tracontent:{tracontent_tag}
tracontent_static_image: !Format tracon/tracontent-static:{tracontent_tag}
tracontent_enable_volumes: true

ingress_public_hostnames:
  - tracontent.127.0.0.1.xip.io
ingress_letsencrypt_enabled: false

# For memcached, rabbitmq and PostgreSQL, choose between a managed (in-cluster) service or
# an external one. For external services, set fooservice_managed: false and point
# fooservice_hostname to the external service, overriding the other defaults if necessary.
# Also please pin the images using a tag other than latest for production.
memcached_managed: true
memcached_image: memcached:alpine
memcached_hostname: memcached

# NOTE: "managed" PostgreSQL should not be considered production-ready.
postgres_managed: true
postgres_image: postgres
postgres_hostname: postgres
postgres_database: tracontent

setup_should_run: true

# Common environment vars for both tracontent and celery pods.
environment:
  - name: POSTGRESQL_HOSTNAME
    value: !Var postgres_hostname
  - name: POSTGRESQL_DATABASE
    value: !Var postgres_database
  - name: POSTGRESQL_USERNAME
    valueFrom:
      secretKeyRef:
        name: postgres
        key: username
  - name: POSTGRESQL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres
        key: password
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: tracontent
        key: secretKey
  - name: ALLOWED_HOSTS
    value: !Join,Var tracontent_public_hostnames
