# tracontent deployment using Kubernetes
# usage: emrichen kubernetes.in.yml | kubectl apply -n tracontent -f -

!Include defaults.in.yml


#############
# MEMCACHED #
#############
---
!If
  test: !Var memcached_managed
  then: !Include memcached/service.in.yml
---
!If
  test: !Var memcached_managed
  then: !Include memcached/deployment.in.yml


##############
# POSTGRESQL #
##############
---
!If
  test: !Var postgres_managed
  then: !Include postgres/service.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/deployment.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/pvc.in.yml

---
!If
  test: !Var postgres_managed
  then: !Include postgres/secret.in.yml


#########################
# GUNICORN (Web server) #
#########################
---
!Include tracontent/service.in.yml
---
!Include tracontent/deployment.in.yml
---
!Include tracontent/pvc.in.yml
---
!Include tracontent/secret.in.yml


###############################
# NGINX (Static file serving) #
###############################
---
!Include nginx/service.in.yml
---
!Include nginx/deployment.in.yml


###########
# INGRESS #
###########
---
!Include ingress.in.yml


##################
# DATABASE SETUP #
##################
---
!If
  test: !Var setup_should_run
  then: !Include jobs/setup.in.yml
