ingress_public_hostnames:
  - 2015.hitpoint.tracon.fi
  - 2016.hitpoint.tracon.fi
  - 2016.tracon.fi
  - 2017.hitpoint.tracon.fi
  - 2017.tracon.fi
  - 2018.tracon.fi
  - 2019.hitpoint.tracon.fi
  - 2019.tracon.fi
  - 2020.hitpoint.tracon.fi
  - 2020.tracon.fi
  - 2021.tracon.fi
  - 2022.tracon.fi
  - blog.tracon.fi
  - r.tracon.fi
  - ry.tracon.fi

postgres_managed: false
postgres_hostname: siilo.tracon.fi
postgres_database: tracontent
postgres_username: tracontent
postgres_ssl: true

redis_managed: false
redis_hostname: redis-ha-haproxy.redis-ha.svc.cluster.local
redis_cache_database: 4
tracontent_secret_managed: false
tracontent_storage_pvc: true
tracontent_storage_pvc_storageclass: longhorn-nfs

tracontent_editor_groups:
  - turska-tracon2022-labour-conitea
  - traconry-hallitus-nykyinen

tracontent_admins:
  - Santtu Pajukanta <santtu@pajukanta.fi>

smtp_server: sr1.pahaip.fi
smtp_default_from_email: root@tracon.fi

setup_should_run: true

ingress_letsencrypt_enabled: true
ingress_letsencrypt_cluster_issuer: letsencrypt-prod
