apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    stack: tracontent
    component: postgres
  name: postgres-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
